# Generated by Django 2.2 on 2019-04-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asl_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='url',
            field=models.CharField(default='Blank URL', max_length=400),
        ),
    ]
